AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Root SAM template for nested stacks

Resources:
  BucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: bucket-stack/template.yaml

  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda-stack/template.yaml
      Parameters:
        SourceBucketName: !GetAtt BucketStack.Outputs.SourceBucketName
        TargetBucketName: !GetAtt BucketStack.Outputs.TargetBucketName
        SNSTopicArn: !GetAtt BucketStack.Outputs.SNSTopicArn
