AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Document Analytics System (PDF, TXT, CSV) with direct S3-to-SNS upload notification

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to subscribe to report notifications

Resources:
  ########################################
  # 1️⃣  SNS Topic for notifications
  ########################################
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  ########################################
  # 2️⃣  DynamoDB Table
  ########################################
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  ########################################
  # 3️⃣  S3 Bucket (directly notifies SNS)
  ########################################
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref SNSTopic
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
          - Event: s3:ObjectCreated:*
            Topic: !Ref SNSTopic
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .txt
          - Event: s3:ObjectCreated:*
            Topic: !Ref SNSTopic
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv

  ########################################
  # 4️⃣  Document Extractor Lambda
  ########################################
  DocumentExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentExtractor
      CodeUri: document_extractor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 90
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBWritePolicy:
            TableName: !Ref DocumentTable
        - LambdaInvokePolicy:
            FunctionName: !Ref DocumentAnalyzerFunction
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          ANALYZER_FUNCTION_NAME: !Ref DocumentAnalyzerFunction
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic

  ########################################
  # 5️⃣  Document Analyzer Lambda
  ########################################
  DocumentAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentAnalyzer
      CodeUri: document_analyzer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 45
      MemorySize: 256
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          TOPIC_ARN: !Ref SNSTopic

  ########################################
  # 6️⃣  Allow S3 → SNS direct publishing
  ########################################
  S3ToSNSPermission:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt DocumentBucket.Arn

Outputs:
  S3UploadBucketName:
    Description: Upload your documents here
    Value: !Ref DocumentBucket

  SNSTopicARN:
    Description: SNS Topic for all notifications
    Value: !Ref SNSTopic

  DocumentExtractorFunctionName:
    Description: Extractor Lambda name
    Value: !Ref DocumentExtractorFunction

  DocumentAnalyzerFunctionName:
    Description: Analyzer Lambda name
    Value: !Ref DocumentAnalyzerFunction
