AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Process uploaded .txt files with simple text analysis, store results in DynamoDB, and send email notifications

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to receive notifications

Resources:
  # S3 Bucket for uploading .txt files
  TextBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "simple-txt-bucket-${AWS::AccountId}-${AWS::Region}"

  # DynamoDB Table to store text analysis results
  TextAnalysisTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TextAnalysisTable
      PrimaryKey:
        Name: file_key
        Type: String

  # SNS Topic for notifications
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TextAnalysisTopic

  # SNS Email Subscription
  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  # Explicitly define the IAM role for the Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow  # Basic logging
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow  # S3 read access
                Action: s3:GetObject
                Resource: !Sub "arn:aws:s3:::${TextBucket}/*"
              - Effect: Allow  # DynamoDB write access
                Action: dynamodb:PutItem
                Resource: !GetAtt TextAnalysisTable.Arn
              - Effect: Allow  # SNS publish access
                Action: sns:Publish
                Resource: !Ref SNSTopic

  # Lambda Function to process .txt files and perform text analysis
  TextAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TextAnalysisProcessor
      CodeUri: document_processor/  # Updated to match your folder name
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TextAnalysisTable
          SNS_TOPIC_ARN: !Ref SNSTopic
      Events:
        TxtUpload:
          Type: S3
          Properties:
            Bucket: !Ref TextBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .txt
    DependsOn:
      - TextBucket
      - LambdaExecutionRole
      - SNSTopic

Outputs:
  UploadBucketName:
    Description: The S3 bucket for uploading .txt files
    Value: !Ref TextBucket
  DynamoDBTableName:
    Description: The DynamoDB table for storing text analysis results
    Value: !Ref TextAnalysisTable
  SNSTopicARN:
    Description: SNS Topic ARN for notifications
    Value: !Ref SNSTopic
