AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Document Analytics with automatic upload notification and text analysis

Parameters:
  SnsEmail:
    Type: String
    Description: Email to receive upload and analysis notifications

Resources:
  # 1️⃣ S3 Bucket
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Ref UploadSNSTopic
    DependsOn: UploadSNSTopicPolicy

  # 2️⃣ SNS Topic for Upload Notifications
  UploadSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentUploadTopic

  UploadSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref UploadSNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref UploadSNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${DocumentBucket}"

  UploadEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref UploadSNSTopic

  # 3️⃣ DynamoDB Table
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  # 4️⃣ SNS Topic for Analysis Reports
  ReportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  ReportEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref ReportSNSTopic

  # 5️⃣ Main Lambda Function (Extractor + Analyzer Combined)
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentProcessor
      CodeUri: document_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 90
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref ReportSNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          REPORT_TOPIC_ARN: !Ref ReportSNSTopic
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
                  - Name: suffix
                    Value: .txt
                  - Name: suffix
                    Value: .csv

Outputs:
  S3BucketName:
    Value: !Ref DocumentBucket
    Description: Upload documents here to trigger analysis

  UploadSNSTopicARN:
    Value: !Ref UploadSNSTopic
    Description: SNS topic that receives upload notifications

  ReportSNSTopicARN:
    Value: !Ref ReportSNSTopic
    Description: SNS topic that receives analysis reports
