AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: One Lambda Document Processor - Extract, Analyze, Notify (No Circular Dependency)

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to receive notifications

Resources:
  # ---------------------
  # S3 Bucket for Uploads
  # ---------------------
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration: {}  # leave empty - SAM will manage event
      BucketName: !Sub "sam-one-lambda-bucket-${AWS::AccountId}"

  # ---------------------
  # DynamoDB Table
  # ---------------------
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  # ---------------------
  # SNS Topic + Email Subscription
  # ---------------------
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  # ---------------------
  # Lambda Function
  # ---------------------
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentProcessor
      CodeUri: document_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 120
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - S3ReadPolicy:
            BucketName: !Sub "sam-one-lambda-bucket-${AWS::AccountId}"
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          TOPIC_ARN: !Ref SNSTopic
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
                  - Name: suffix
                    Value: .txt
                  - Name: suffix
                    Value: .csv

Outputs:
  UploadBucketName:
    Description: Upload bucket for documents
    Value: !Ref DocumentBucket
  SNSTopicARN:
    Description: SNS Topic for notifications
    Value: !Ref SNSTopic
  LambdaFunctionName:
    Description: The name of the processor Lambda
    Value: !Ref DocumentProcessorFunction
