AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: One Lambda to process .txt files, store results in DynamoDB, and notify via SNS

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to receive notifications
  UploadBucketName:
    Type: String
    Description: Unique name for the S3 bucket (must be globally unique)

Resources:
  # ---------------------
  # S3 Bucket (parameterized)
  # ---------------------
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  # ---------------------
  # DynamoDB Table
  # ---------------------
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  # ---------------------
  # SNS Topic + Email Subscription
  # ---------------------
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  # ---------------------
  # Lambda Function
  # ---------------------
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TxtDocumentProcessor
      CodeUri: document_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - S3ReadPolicy:
            BucketName: !Ref UploadBucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          TOPIC_ARN: !Ref SNSTopic
      Events:
        TxtUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucketName
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .txt

Outputs:
  UploadBucketName:
    Description: The S3 bucket where you upload .txt files
    Value: !Ref DocumentBucket
  SNSTopicARN:
    Description: SNS Topic ARN for notifications
    Value: !Ref SNSTopic
  LambdaFunctionName:
    Description: The name of the Lambda function
    Value: !Ref DocumentProcessorFunction
