AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: One-Lambda Document Analytics System (S3 → Lambda → SNS)

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to receive document analytics reports

Resources:
  ###########################################################
  #  S3 Bucket for uploads
  ###########################################################
  DocumentBucket:
    Type: AWS::S3::Bucket

  ###########################################################
  #  DynamoDB Table for storing extracted text
  ###########################################################
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  ###########################################################
  #  SNS Topic for sending reports
  ###########################################################
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  ###########################################################
  #  Lambda Function: Single unified app
  ###########################################################
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentProcessor
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 90
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBWritePolicy:
            TableName: !Ref DocumentTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          TOPIC_ARN: !Ref SNSTopic
      Events:
        PdfUpload:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
        TxtUpload:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .txt
        CsvUpload:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv

Outputs:
  UploadBucket:
    Description: Upload documents to this S3 bucket
    Value: !Ref DocumentBucket

  ReportTopic:
    Description: SNS Topic ARN for document reports
    Value: !Ref SNSTopic
