AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Document Analytics - S3 Upload -> SNS Notification + Lambda Analyzer

Parameters:
  SnsEmail:
    Type: String
    Description: Email to receive upload and analysis notifications

Resources:
  ##################################################
  # 1️⃣ SNS Topic for Upload Notifications
  ##################################################
  UploadSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentUploadTopic

  UploadEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref UploadSNSTopic

  ##################################################
  # 2️⃣ DynamoDB Table for Document Metadata
  ##################################################
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  ##################################################
  # 3️⃣ SNS Topic for Report Notifications
  ##################################################
  ReportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  ReportEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref ReportSNSTopic

  ##################################################
  # 4️⃣ S3 Bucket (create first, then attach notification)
  ##################################################
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sam-doc-analytics-${AWS::AccountId}-${AWS::Region}"

  ##################################################
  # 5️⃣ S3 Bucket Notification for SNS (separate resource)
  ##################################################
  S3BucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref DocumentBucket
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Ref UploadSNSTopic
    DependsOn:
      - UploadSNSTopicPolicy

  ##################################################
  # 6️⃣ SNS Topic Policy (allow S3 to publish)
  ##################################################
  UploadSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref UploadSNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref UploadSNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::sam-doc-analytics-${AWS::AccountId}-${AWS::Region}"

  ##################################################
  # 7️⃣ Lambda - Extract + Analyze + Report
  ##################################################
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DocumentProcessorFunction
      CodeUri: document_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 90
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref ReportSNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          REPORT_TOPIC_ARN: !Ref ReportSNSTopic
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
                  - Name: suffix
                    Value: .txt
                  - Name: suffix
                    Value: .csv

Outputs:
  S3BucketName:
    Value: !Ref DocumentBucket
    Description: S3 bucket for uploading documents

  UploadSNSTopicARN:
    Value: !Ref UploadSNSTopic
    Description: SNS topic for upload notifications

  ReportSNSTopicARN:
    Value: !Ref ReportSNSTopic
    Description: SNS topic for analysis reports
