AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Complete Document Analytics System (PDF, TXT, CSV) deployed via AWS SAM

Parameters:
  SnsEmail:
    Type: String
    Description: Email address to subscribe to report notifications

Resources:
  ############################################################
  # DynamoDB Table
  ############################################################
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DocumentTextTable
      PrimaryKey:
        Name: document_id
        Type: String

  ############################################################
  # SNS Topic and Email Subscription
  ############################################################
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DocumentReportTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SnsEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

  ############################################################
  # Lambda Function: Analyzer
  ############################################################
  DocumentAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentAnalyzer
      CodeUri: document_analyzer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 512
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentTable
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSTopic
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          TOPIC_NAME: !Ref SNSTopic

  ############################################################
  # Lambda Function: Extractor (no S3 event inline)
  ############################################################
  DocumentExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentExtractor
      CodeUri: document_extractor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "sam-doc-analytics-bucket-${AWS::AccountId}"
        - DynamoDBWritePolicy:
            TableName: !Ref DocumentTable
        - LambdaInvokePolicy:
            FunctionName: !Ref DocumentAnalyzerFunction
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DocumentTable
          ANALYZER_FUNCTION_NAME: !Ref DocumentAnalyzerFunction

  ############################################################
  # Permission for S3 to invoke Extractor Lambda
  ############################################################
  DocumentExtractorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DocumentExtractorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  ############################################################
  # S3 Bucket with NotificationConfiguration
  ############################################################
  DocumentBucket:
    Type: AWS::S3::Bucket
    DependsOn: DocumentExtractorPermission
    Properties:
      BucketName: !Sub "sam-doc-analytics-bucket-${AWS::AccountId}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt DocumentExtractorFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
                  - Name: suffix
                    Value: .txt
                  - Name: suffix
                    Value: .csv

Outputs:
  S3UploadBucketName:
    Description: S3 bucket where documents should be uploaded
    Value: !Ref DocumentBucket

  SNSTopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref SNSTopic

  DocumentExtractorFunctionName:
    Description: Name of the Lambda function that extracts text from documents
    Value: !Ref DocumentExtractorFunction

  DocumentAnalyzerFunctionName:
    Description: Name of the Lambda function that analyzes processed documents
    Value: !Ref DocumentAnalyzerFunction
